name = "tiktok-downloader"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
RAPIDAPI_KEY = "e0446dfc14msh25c8592ef0dee92p112e88jsnf6b483c4549d"
TIKTOK_API_HOST = "tiktok-video-no-watermark2.p.rapidapi.com"
YOUTUBE_API_HOST = "youtube-media-downloader.p.rapidapi.com" 