name = "video-downloader"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = []

[env.production]
routes = [
  { pattern = "tiktoktool.org/download*", zone_id = "9fcc87dcbc1e73ef263bb31dd0b1dc9f" }
] 